
/**
* InvalidQTY.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from StockControlInterface.idl
* Tuesday, 16 February 2010 00:39:54 o'clock GMT
* 
* Sample program for use with IBM Integration Bus
* © Copyright International Business Machines Corporation 2010 
* Licensed Materials - Property of IBM
*/

public final class InvalidQTY extends org.omg.CORBA.UserException implements org.omg.CORBA.portable.IDLEntity
{
  public int currentQuantity = (int)0;
  public int changeQtyRequested = (int)0;

  public InvalidQTY ()
  {
    super(InvalidQTYHelper.id());
  } // ctor

  public InvalidQTY (int _currentQuantity, int _changeQtyRequested)
  {
    super(InvalidQTYHelper.id());
    currentQuantity = _currentQuantity;
    changeQtyRequested = _changeQtyRequested;
  } // Init ctor

  public InvalidQTY (String $reason, int _currentQuantity, int _changeQtyRequested)
  {
    super(InvalidQTYHelper.id() + "  " + $reason);
    currentQuantity = _currentQuantity;
    changeQtyRequested = _changeQtyRequested;
  } // ctor

} // class InvalidQTY
