
/**
* SKUNameAlreadyExist.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from StockControlInterface.idl
* Tuesday, 16 February 2010 00:39:54 o'clock GMT
* 
* Sample program for use with IBM Integration Bus
* © Copyright International Business Machines Corporation 2010 
* Licensed Materials - Property of IBM
*/

public final class SKUNameAlreadyExist extends org.omg.CORBA.UserException implements org.omg.CORBA.portable.IDLEntity
{
  public int sku = (int)0;

  public SKUNameAlreadyExist ()
  {
    super(SKUNameAlreadyExistHelper.id());
  } // ctor

  public SKUNameAlreadyExist (int _sku)
  {
    super(SKUNameAlreadyExistHelper.id());
    sku = _sku;
  } // Init ctor

  public SKUNameAlreadyExist (String $reason, int _sku)
  {
    super(SKUNameAlreadyExistHelper.id() + "  " + $reason);
    sku = _sku;
  } // ctor

} // class SKUNameAlreadyExist
