
/**
* StockControlManagementSystemOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from StockControlInterface.idl
* Tuesday, 16 February 2010 00:39:54 o'clock GMT
* 
* Sample program for use with IBM Integration Bus
* © Copyright International Business Machines Corporation 2010 
* Licensed Materials - Property of IBM
*/

public interface StockControlManagementSystemOperations 
{
  int getSKU (String name) throws InvalidSKUName;
  String getSKUName (int sku) throws InvalidSKU;
  void addStock (int sku, int number, org.omg.CORBA.IntHolder quantity) throws InvalidSKU;
  void reduceStock (int sku, int number, org.omg.CORBA.IntHolder quantity) throws InvalidSKU, InvalidQTY;
  int getStockLevel (int sku) throws InvalidSKU;
  double getPrice (int sku) throws InvalidSKU;
  void setPrice (int sku, double price) throws InvalidSKU;
  void createNewStockItem (String name, org.omg.CORBA.IntHolder sku) throws InvalidSKU, SKUNameAlreadyExist;
  void deleteStockItem (int sku) throws InvalidSKU;
} // interface StockControlManagementSystemOperations
