
/**
* StockControlManagementSystemHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from StockControlInterface.idl
* Tuesday, 16 February 2010 00:39:54 o'clock GMT
* 
* Sample program for use with IBM Integration Bus
* © Copyright International Business Machines Corporation 2010 
* Licensed Materials - Property of IBM
*/

public final class StockControlManagementSystemHolder implements org.omg.CORBA.portable.Streamable
{
  public StockControlManagementSystem value = null;

  public StockControlManagementSystemHolder ()
  {
  }

  public StockControlManagementSystemHolder (StockControlManagementSystem initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StockControlManagementSystemHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StockControlManagementSystemHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StockControlManagementSystemHelper.type ();
  }

}
