
/**
* StockControlManagementSystemHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from StockControlInterface.idl
* Tuesday, 16 February 2010 00:39:54 o'clock GMT
* 
* Sample program for use with IBM Integration Bus
* © Copyright International Business Machines Corporation 2010 
* Licensed Materials - Property of IBM
*/

abstract public class StockControlManagementSystemHelper
{
  private static String  _id = "IDL:StockControlManagementSystem:1.0";

  public static void insert (org.omg.CORBA.Any a, StockControlManagementSystem that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static StockControlManagementSystem extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (StockControlManagementSystemHelper.id (), "StockControlManagementSystem");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static StockControlManagementSystem read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_StockControlManagementSystemStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, StockControlManagementSystem value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static StockControlManagementSystem narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof StockControlManagementSystem)
      return (StockControlManagementSystem)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      return new _StockControlManagementSystemStub (delegate);
    }
  }

  public static StockControlManagementSystem unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof StockControlManagementSystem)
      return (StockControlManagementSystem)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      return new _StockControlManagementSystemStub (delegate);
    }
  }

}
